server:
  port: ${PORT:8086}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ms-pdp-search
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:25}
          max-idle: ${REDIS_POOL_MAX_IDLE:25}
          min-idle: ${REDIS_POOL_MIN_IDLE:10}
          max-wait: ${REDIS_POOL_MAX_WAIT:500}
      timeout: ${REDIS_TIMEOUT:5000}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  security:
    user:
      name: ${USER_NAME_SECURITY:212L234xdd=?sa1$3LLM#04252025}
      password: ${PASSWORD_SECURITY:323&=?!2212LOS2sde#3as3sad32}
